name: fido_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.2

# Add regular dependencies here.
dependencies:
  dcli_core: ^3.0.3
  path: ^1.8.3
  random_string: ^2.3.1
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_secure_cookie: ^1.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
